#!/usr/bin/env python3
"""Build the pages GitHub Pages serves from one source, src/index.src.html:
  index.html       Case Draw  (freehand drawing)
  beck/index.html  Beck       (Drawn Codes grid drawing: 45/90 degree lines, after the tube map)
Vendored libraries and geo.js are inlined; the app reads its mode from APP_MODE."""
import re, pathlib
root = pathlib.Path(__file__).parent
src = (root / "src/index.src.html").read_text()
earcut = (root / "src/vendor/earcut.min.js").read_text()
pcl = re.sub(r"//# sourceMappingURL=.*", "", (root / "src/vendor/polygon-clipping.umd.min.js").read_text())
geo = (root / "src/geo.js").read_text()

def module_body(path):
    """An ES module as plain script text: imports dropped, export keywords removed."""
    s = (root / path).read_text()
    s = re.sub(r"^import .*?;\s*$", "", s, flags=re.M)
    return re.sub(r"^export ", "", s, flags=re.M)

drawncodes = ("(() => {\n" + module_body("src/vendor/drawncodes/engine.js") + "\n" + module_body("src/vendor/drawncodes/silhouette.js") +
              "\nwindow.DrawnCodes = { GridModel, computeFill, buildInk, traceSilhouette, STROKE, UP, RIGHT, DOWN, LEFT, UR, DR, DL, UL, TOUCHED };\n})();")

def page(mode, title):
    libs = f"""<script>/* earcut 2.2.4 — ISC License, Copyright (c) 2016, Mapbox */
{earcut}
</script>
<script>/* polygon-clipping 0.15.7 — MIT License, Copyright (c) 2018 Mike Fogel (bundles splaytree, robust-predicates, bignumber.js) */
{pcl}
</script>
<script>
{geo}
</script>
"""
    if mode == "beck":
        libs += f"<script>/* Drawn Codes engine (vendored, see src/vendor/drawncodes/README.txt) */\n{drawncodes}\n</script>\n"
    libs += "<script>/* phone presets: generated by tools/make_phones.py from Apple's dimensional drawings */\n" + (root / "src/phones.js").read_text() + "\n</script>\n"
    libs += f'<script>window.APP_MODE = "{mode}";</script>\n'
    out = src.replace("<script>\n(() => {", libs + "<script>\n(() => {", 1)
    return out.replace("<title>Case Draw</title>", f"<title>{title}</title>", 1)

for mode, title, path in [("draw", "Case Draw", "index.html"), ("beck", "Beck", "beck/index.html")]:
    out = page(mode, title)
    (root / path).parent.mkdir(exist_ok=True)
    (root / path).write_text(out)
    print(f"wrote {path} ({len(out):,} bytes)")
